#%RAML 1.0 NamedExample
rou:
  [
{
"companyCode":"TransNational", "originLocation": {
"locationCode": "BEN-SG", "locationDesc": "Beauna VistaSingapore"
},
"destinationLocation": { "locationCode": "KLG-MY", "locationDesc": "Klang Malaysia"
}
},
{
"companyCode":"TransNational", "originLocation": {
"locationCode": "BEN-SG", "locationDesc": "Beauna VistaSingapore"
},
"destinationLocation": { "locationCode": "KLG-MY", "locationDesc": "Klang Malaysia"
}
},
{
"companyCode":"TransNational", "originLocation": {
"locationCode": "BEN-SG", "locationDesc": "Beauna VistaSingapore"
},
"destinationLocation": { "locationCode": "KLG-MY", "locationDesc": "Klang Malaysia"
}
}


]
